### ISSUE TITLE
[Feature Request] Remove twice track in Shuffle or playlist

### ISSUE THREAD

**Issue by Mika64** [airsonic/airsonic#1016] opened 2019-04-15 10:22 UTC
When you have two same track in your playlist (by Shuffle or not), current playlist take the first of this two track for current played song. This is a problem because your enter in a loop between this two track.

Suggest : Add button for remove all double in current playlist.

**Comment by eharris** [comment] 2019-10-02 07:50
I believe this is a duplicate of #804.

**Closed by eharris** 2019-10-02 07:50 UTC
Labels: duplicate, enhancement
