### ISSUE TITLE
error messages invisible in Back in Black theme

### ISSUE THREAD

**Issue by postags** [airsonic/airsonic#535] opened 2017-08-26 22:08 UTC
![2017-08-25 21_26_54-chillin - x i b sweizy gang ent - airsonic - waterfox](https://user-images.githubusercontent.com/22846348/29745486-4e4a1a28-8a70-11e7-939b-aba49323985d.png)

**Comment by muff1nman** [comment] 2017-08-27 01:16
Closing - This is a duplicate of #536 and related to #517.

**Comment by postags** [comment] 2017-08-27 02:00
It's a separate issue, just with the same illustrating image. The text in the dark grey side of the table is not visible unless highlighted.

**Comment by muff1nman** [comment] 2017-08-27 02:05
Ah I see.

**Comment by hschroedl** [comment] 2017-08-30 21:24
I played around with this a bit. Basically `head.jsp` has to be included in `error.jsp`. 
In order to force the error page I basically made some other view return the AccessDenied view, e.g. in `StarredController.java`

    return new ModelAndView("accessDenied");

and copied the contents of `error.jsp` in there. Didn't manage to get the error page any other way. Would really like to know how to do that though :man_shrugging:

**Comment by hschroedl** [comment] 2017-09-25 07:04
@muff1nman Ping, I think this can be closed ;)

**Closed** 2017-09-25 08:42 UTC
Labels: bug
