### ISSUE TITLE
Multiple copies of same song in playlist not handled correctly

### ISSUE THREAD

**Issue by affert** [airsonic/airsonic#1830] opened 2020-12-05 19:37 UTC
## Problem description

I have a playlist of Christmas music.  I have several albums. Between each album, there are a few individual favorite songs I want to play each time. Airsonic doesn't track which item it is in the playlist correctly:

It highlights both instances of the song on the playlist while it is playing. When the song finishes, it always plays the song after the first instance of the repeated song.

### Steps to reproduce

1. Have at least 3 songs (SongA, SongB, SongC)
2. Make a new playlist.
3. Add SongA
4. Add SongB
5. Add SongA (again)
6. Add SongC
7. Listen to playlist.  You'll hear SongA, then SongB, then SongA, then SongB (NOT SongC as I'd expect)
8. Sadness

## System information

About:
Version | 10.6.2-RELEASE – May 3, 2020
Server | Apache Tomcat/8.5.51, java 1.8.0_275, Linux (145.4 MB / 659.5 MB)

Ubuntu  20.10 (sever edition)

 java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.10-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

No proxy server

Occurs in web interface (Windows 10, Firefox version 83)

English

Addional note:
This does NOT happen when listening on my Andriod using DSUB

**Comment by eharris** [comment] 2020-12-06 02:36
Dupe of #804.

**Closed by eharris** 2020-12-06 02:36 UTC
