### ISSUE TITLE
media path cannot contain spaces

### ISSUE THREAD

**Issue by fejjj** [airsonic/airsonic#792] opened 2018-08-30 06:19 UTC
## Problem description

media path can not contain whitespace

### Steps to reproduce

"/media/user/external hard drive/My Music" returns "folder not found"

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

i have tried replacing the whitespace with %20, +, escaping with forward slash, containing the path in both single and double quotes.  always returns "folder not found"

works ok in subsonic..

## System information

    Airsonic version: 10.1.2-RELEASE – July 28, 2018
    Operating system: ubuntu-mate 18.04
    Proxy server: nginx/1.14.0
    Client: google chrome (windows 7)

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by eharris** [comment] 2019-09-16 19:22
I'm not able to reproduce this on the current head.  I'm guessing it either got fixed or was an end-user config problem.  Closing.

**Closed by eharris** 2019-09-16 19:22 UTC
Labels: backend, can't reproduce
