### ISSUE TITLE
FLAC Playback hangs

### ISSUE THREAD

**Issue by RedGreen007** [airsonic/airsonic#1172] opened 2019-07-18 00:15 UTC
## Problem description

Updated to 10.4.0 and in both Chrome and Firefox the song will play until around the 1:50 mark and then just stop. The ticker on the timer will continue but no music. Then after about 10 seconds it will continue playing where it left off before. 

### Steps to reproduce

First thing I did was remove FLAC from the list for transcoding. 

Play a song and it will eventually just hang and then continue playing. 

If I add FLAC back in, it will still hang at the same point.

## System information

 * **Airsonic version**: 10.4.0
 * **Operating system**: Ubuntu 18.04
 * **Java version**:  openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

 * **Proxy server**: None
 * **Client**: FireFox and Chrome. Latest builds.

## Additional notes

If someone can recommend a program to record a desktop video of what happens I will take one of it.

**Comment by jvoisin** [comment] 2019-07-18 07:55
Do you have anything in the logs?

**Comment by RedGreen007** [comment] 2019-07-18 08:21
[log.txt](https://github.com/airsonic/airsonic/files/3405491/log.txt)

**Comment by dalecooper** [comment] 2019-07-24 09:22
I'm having a probably related issue with FLAC since 10.4.0. Let me know if you want me to file a new issue though.
Not easy to explain but I'll do my best.

When a track starts playing, the player doesn't immediately display the real track length, but instead displays something like 0:12, then quickly updates to 0:33, 0:47 and so on until it reaches 1:07. Then it stops updating for about 20 seconds, updates to 1:38, hangs a little more then updates to 2:14 and so on. The 1:07, 1:38, 2:14 values are always the same no matter what track is playing.
The loading bar is updated every time accordingly to the (track length / position) ratio, but at some point it reaches the end before the real track length is loaded, so the player naturally skips to the next track. This happens mostly with tracks longer than ~8 minutes.

See the short screencast below.

![ezgif-2-e688cd6998bf](https://user-images.githubusercontent.com/16813929/61781722-65059180-adf4-11e9-8d05-98e14c793c0e.gif)

Bandwidth is definitely not a problem, and the issue occurs with Firefox as well as Chrome. There is nothing of interest in the logs, it's just as a normal play queue. MP3s play just fine.

I'm happy to help with any more info.

**Comment by iGormilhit** [comment] 2019-08-01 09:45
@dalecooper Quite the same here. I have to downgrade to 1.20.1 (since a bug in the 1.30.x serie makes airsonic not usable).

**Comment by dalecooper** [comment] 2019-08-01 09:51
After playing a bit with the settings, I've found out that my issue happens with transcoding only.
Tested with 2 transcoding methods :
- the default FFMPEG one
- 2 steps FLAC > Lame
Same issue with both methods
If I completely disable transcoding for FLAC on the web player, I experience the exact same issue described by @RedGreen007
So for now I'm also using 10.2.1
Still happy to help with any more info or testing.

**Comment by iGormilhit** [comment] 2019-11-08 07:36
I'm testing 10.5.0, with the same behaviour. I'm wondering if it could be the ffmpeg version, which is on my debian stretch `7:3.2.14-1~deb9u1`.

**Comment by dorel14** [comment] 2020-02-02 16:19
Hello 
Same for me here with 10.5. on debian stretch / Tomcat 9 / Openjdk 11 flac file hang in the middle and never restart.
There are a lot of error in browser console (Chrome)
'Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH'
'GET https://myserver.com/stream?player=4&id=34175 net::ERR_CONTENT_LENGTH_MISMATCH 206'

**Comment by pozgo** [comment] 2020-02-02 18:39
For all of those like me who love Hi-Res audio, I have settings like below working perfectly

Name|Convert From|Convert to| Step 1|Step2
-- | -- | -- | -- | --
|flac|... any...|flac|`ffmpeg -i %s -af aformat=s32:176000 -f flac -`|| 

The above encodes to a 176 kHz 24-bit sample, stored as 32-bits 

In my case, most of my files are already Hi-Res so not losing any quality.

**Comment by iGormilhit** [comment] 2020-04-24 09:37
I'm running the `10.6.1` and **everything** is perfect! From my point of view, it's fixed! (ping @jvoisin )

Thanks a lot!

**Comment by tesshucom** [comment] 2020-05-11 04:32
It seems that the fix has been confirmed, so I'll close it. If you encounter a similar issue, please report it again.

**Closed by tesshucom** 2020-05-11 04:32 UTC
Labels: in: web-playback, status: feedback-provided, type: bug
