### ISSUE TITLE
Unwanted characters appended to text in buttons in 10.1.1

### ISSUE THREAD

**Issue by pacija** [airsonic/airsonic#672] opened 2018-01-09 10:17 UTC
## Problem description

"More Actions" button in player and "Selected Songs" button in album menu got unwanted characters appended to the end of containing text.

### Steps to reproduce

Upgrade 10.1.0 to 10.1.1 and log into airsonic web interface.

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: FreeBSD 11.1-RELEASE-p6 amd64
 * **Proxy server**: apache24-2.4.29
 * **Client**: firefox-57.0.3,1 and chromium-61.0.3163.100_5

## Additional notes
Chromium has â€| appended, Firefox has â| (no euro sign)

All my tracks' filenames are UTF-8. They play, and are displayed in web interface fine. My tomcat environment is set from rc.conf:
```
tomcat8_env="LANG=en_US.UTF-8 TZ=Europe/Belgrade"
```

I've attached screenshot from Chromium.

![airsonic](https://user-images.githubusercontent.com/14246467/34715779-1006a7b2-f52e-11e7-94ab-3dee9e3c41e6.jpg)

**Comment by jooola** [comment] 2018-01-09 10:53
Duplicate of #665 
More infos @ #645

**Closed by jooola** 2018-01-09 10:53 UTC
