### ISSUE TITLE
Facebook appends unique ID that breaks share link

### ISSUE THREAD

**Issue by 151henry151** [airsonic/airsonic#1398] opened 2019-11-07 15:54 UTC
## Problem description

When you take a share link, for example `https://airsonic.romp.network/ext/share/CigIu?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL2V4dC9zaGFyZS9DaWdJdSIsImV4cCI6MTYwNDc2NDA4MH0.7TaLbH7WRVP5Tf3IJsyXyS_jdF1NHbK-oB2gmNsFsHY` and  you put it in a comment thread on facebook or share it on facebook, facebook appends a unique ID on the end of the link which breaks the link, like this: `https://airsonic.romp.network/ext/share/CigIu?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXRoIjoiL2V4dC9zaGFyZS9DaWdJdSIsImV4cCI6MTYwNDc2NDA4MH0.7TaLbH7WRVP5Tf3IJsyXyS_jdF1NHbK-oB2gmNsFsHY&fbclid=IwAR2O0p387j3Ra7eUVUJY22g2i3w-8UsSCk9pXyLe7EuJbc6fYxriKCXfwUQ`

### Steps to reproduce

1. Make a share link to music you have the legal right to share
2. Paste that share link as a comment in a facebook thread
3. Click that share link and observe the fbclid string appended to the end breaking the link.

## System information

 * **Airsonic version**: 10.4.1-RELEASE – October 14, 2019
 * **Operating system**: 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
 * **Java version**: openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~deb9u1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

 * **Proxy server**: Apache Tomcat/8.5.42

 * **Client**: Firefox 68.2.0esr (64-bit)
 * **Language**: English

## Additional notes
Enjoy that music share link, it's a demo from my band, ROMP!

**Comment by eharris** [comment] 2019-11-07 17:46
Duplicate of #1212

**Closed by eharris** 2019-11-07 17:46 UTC
