### ISSUE TITLE
Clementine cannot play via Subsonic server API

### ISSUE THREAD

**Issue by ndandanov** [airsonic/airsonic#1211] opened 2019-08-15 14:35 UTC
## Problem description

After updating from Airsonic **v10.1.1** to **v10.4.0**, the Clementine player is no longer able to play via the **Subsonic server API**.

I tried to clean up all working tomcat files and to deploy the application again, but the issue still persists.

Could this have been caused by the following change introduced in **v10.3.0**?
```
Security:
Avoid logging sensitive URL parameters in the Subsonic API
```

The request URL is similar to:
```
127.0.0.1 - - [15/Aug/2019:17:13:05 +0300] "GET //rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:214e696b69313631313932&id=2436 HTTP/1.0" 500 4874
```

Here is an excerpt from the airsonic logs:

```
2019-08-15 16:49:38.433 ERROR --- o.s.b.w.support.ErrorPageFilter          : Forwarding to error page from request [/rest/stream.view] due to exception [The request was rejected because the URL was not normalized.]

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:248) ~[spring-security-web-4.2.12.RELEASE.jar:4.2.12.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193) ~[spring-security-web-4.2.12.RELEASE.jar:4.2.12.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) ~[spring-security-web-4.2.12.RELEASE.jar:4.2.12.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130) [spring-boot-1.5.21.RELEASE.jar:1.5.21.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-1.5.21.RELEASE.jar:1.5.21.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105) [spring-boot-1.5.21.RELEASE.jar:1.5.21.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123) [spring-boot-1.5.21.RELEASE.jar:1.5.21.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) [catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) [tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) [tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
```

### Steps to reproduce

1. *Set up [Clementine](https://www.clementine-player.org) to work with the Airsonic instance via the Subsonic server API*
2. *Let Clementine refresh the library catalogue*
3. *Try to start any item from the library*

## System information

 * **Airsonic version**: *v10.4.0*
 * **Operating system**: *Armbian Debian Linux 9.8, kernel 4.19.20-sunxi #5.75 SMP Sat Feb 9 19:02:47 CET 2019 armv7l*
 * **Java version**: *Java 1.8.0_201*
 * **Proxy server**: *nginx proxy server (the issue appeared after running ~1 year with unchanged nginx settings so perhaps it would not be the cause)*
 * **Client**: *Clementine version 1.3.1-702-g3b76fa627*

## Additional notes

As a side note, for some time the tab for settings is missing (#531) and I cannot go to Shared media, Personal or Players without getting a 403 and `Access is denied` error. Nothing gets printed into logs and there's no exception given. There issues are also described [here](https://www.reddit.com/r/airsonic/comments/c0spzk/403_access_denied_cant_see_settings/), but they were there in the previous install, too, so I do not think this is the cause.

Thanks in advance!

**Comment by eharris** [comment] 2019-08-15 19:19
I'm using Clementine with the Subsonic API on Debian stretch with the current master head (which isn't that much different from 10.4), and it seems to work fine.  I think I've also used Clementine with the Subsonic API with 10.4, but I'd have to downgrade to check.

**Comment by eharris** [comment] 2019-08-15 19:25
The URL your request had looks suspicious.  I don't think it should start with two slashes, and there is usually a path segment before the `/rest/` part, like `GET /airsonic/rest/`...  You might look into your webserver/proxy config to see if there's some translation causing that?

> `"GET //rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:214e696b69313631313932&id=2436 HTTP/1.0"`

**Comment by ndandanov** [comment] 2019-08-16 07:59
Thank you for your feedback, @eharris!

My airsonic instance is installed in `tomcat` and is configured to listen on the root location `\` and not on `/airsonic`. The same is true for my `nginx` configuration - I have `music.mydomain.tld` as a separate domain name. Perhaps this could be the culprit for the requests URL.

I found that my configuration of `airsonic` in `tomcat` is not the standard one described in the documentation. I had installed it a year ago and cannot really remember why I have configured it that way, but the extracted `.war` contents reside in the `deploy` directory of my tomcat installation and I have an additional configuration file under `conf/Catalina/localhost/airsonic.xml`.

Perhaps it would be best to try to clean install `airsonic` and see whether it works as designed.

**Comment by eharris** [comment] 2019-09-15 12:36
Please let us know if the problem persisted after a clean reinstall.  Otherwise this will probably be closed as caused by a mis-configuration.

**Comment by eharris** [comment] 2019-09-23 20:35
Closing due to no further followup.

**Closed by eharris** 2019-09-23 20:35 UTC

**Comment by ndandanov** [comment] 2020-05-27 10:08
Sorry for the very delayed followup, @eharris!

Today I managed to fix the issue and it turned out it was a simple configuration in `clementine` - one has to just make sure that the URL in the subsonic settings is set correctly - `https://music.mydomain.tld` instead of `https://music.mydomain.tld/`. The trailing slash was causing the issues I encountered.

Namely, I noticed in the web server (`nginx` in my case) log the following requests:
```
192.168.1.11 - - [27/May/2020:12:49:56 +0300] "GET /rest/getCoverArt.view?id=1717&id=1717 HTTP/1.1" 200 223 "-" "Clementine 1.4 rc1"
192.168.1.11 - - [27/May/2020:12:49:56 +0300] "GET //rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:214e696b69313631313932&id=1717 HTTP/1.1" 500 4893 "-" "Clementine 1.4 rc1"
```

Note that the double slash in `//rest` was causing the issues.
When testing with the proper URL using `httpie`:
```
http GET "https://music.dandanovi.ml/rest/stream.view?v=1.8.0&c=Clementine&u=admin&p=enc:214e696b69313631313932&id=1717"
```

I got a correct response:
```
2020-05-27 12:51:58.971  INFO --- o.a.p.c.StreamController                 : Streaming request for [/path/to/some/music.mp3] with range [null]
2020-05-27 12:51:58.974  INFO --- o.a.p.io.PlayQueueInputStream            : 127.0.0.1: admin listening to some/music.mp3
2020-05-27 12:51:59.071  INFO --- o.a.p.c.StreamController                 : 127.0.0.1: Client unexpectedly closed connection while loading http://music.mydomain.tld/rest/stream.view?v=1.8.0&c=Clementine&id=1717&p=<hidden>&u=<hidden> (java.io.IOException: Connection reset by peer)
```

Before realizing this is the root cause, I installed the latest `tomcat` 9 (9.0.35) and reinstalled `airsonic` with the latest stable version (`v10.6.2`) as specified in the docs. The unpacked `war` files are served from `tomcat_root/webapps/ROOT`. I have not changed anything in the database.

Thanks for the great product! :)
