### ISSUE TITLE
Last song in playlist repeating.

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#1160] opened 2019-07-04 16:18 UTC
On current master branch, the last song in the playlist seems to repeat without end.

**Comment by fxthomas** [comment] 2019-07-04 20:29
Caused by the workaround in #1080, will be fixed once https://github.com/mediaelement/mediaelement/issues/2650 is taken care of (unless we find a better workaround).

**Comment by Kieltux** [comment] 2019-07-17 18:29
Just for the history (and maybe for other people): airsonic release 10.4.0 does still have the problem with repeating the last song from a playlist.

**Comment by eharris** [comment] 2019-07-30 06:28
@fxthomas Do you have any ideas on how to fix this?  I'm not really a JS guy but would it be possible to add a check if it tries to play the same streamUrl again without having had user intervention, and if so stop?

**Comment by fxthomas** [comment] 2019-08-13 21:37
@eharris Feel free to work on this if you have time, I'm going on holidays until mid-September so I definitely won't work on this until then... I think it is possible to do it as you propose, provided we make really sure that we don't accidentally trigger the race conditions in MEJS.

**Comment by Mycah** [comment] 2019-09-05 16:12
It seems to repeat the entire playlist for me, no matter what I have the repeat setting at.

**Comment by nanawel** [comment] 2019-09-19 09:26
Only repeating the last track in my case, but yes, on `10.4.0-RELEASE` this bug's still here.

**Closed** 2019-09-28 14:05 UTC
Labels: playback, regression
