### ISSUE TITLE
Maven Package Test Fail

### ISSUE THREAD

**Issue by RedGreen007** [airsonic/airsonic#1163] opened 2019-07-08 08:15 UTC
```
[ERROR] Failures:
[ERROR]   SearchServiceTestCase.testSearchTypical:237 (15) Specify album 'Ravel - Chamber Music', and get songs. The first song is  expected:<0[1 - Gaspard de la Nuit - i. Ondine]> but was:<0[2 - Gaspard de la Nuit - ii. Le Gibet]>
[INFO]
[ERROR] Tests run: 161, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Airsonic 10.4.0-SNAPSHOT:
[INFO]
[INFO] Airsonic ........................................... SUCCESS [  2.579 s]
[INFO] Subsonic REST API .................................. SUCCESS [ 13.869 s]
[INFO] Sonos API .......................................... SUCCESS [ 15.400 s]
[INFO] Airsonic Main ...................................... FAILURE [  01:06 h]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 h
[INFO] Finished at: 2019-07-07T15:35:48-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project airsonic-main: There are test failures.
[ERROR]
[ERROR] Please refer to /home/pi/airsonic/airsonic-main/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :airsonic-main
```

I bypassed it by running `mvn clean package -DskipTests`

If you need any other information on it let me know. I bypassed the tests and it worked just fine.

**Comment by jvoisin** [comment] 2019-07-08 08:24
I guess you used `mvn clean package` to launch the testuite?

**Comment by RedGreen007** [comment] 2019-07-08 08:25
Correct.

**Comment by jvoisin** [comment] 2019-07-08 08:31
I can't reproduce this locally with the latest master :/

**Comment by RedGreen007** [comment] 2019-07-08 08:33
I will download it against and try it. If you can't it could just be a local error. I'll close it for now since you can't recreate it.

**Comment by antgel** [comment] 2019-07-17 12:58
For what it's worth, I also see this (trying to build 10.4.0 from git checkout).

**Comment by jvoisin** [comment] 2019-07-17 22:52
@antgel this might sound like a stupid suggestion, but can you reboot and try again? I'm suspecting that it's related to temporary files that aren't deleted between runs.

**Comment by RedGreen007** [comment] 2019-07-17 23:45
I tried to do this on another PC but couldn't get Maven to point to the right JDK cause Ubuntu decided it would just ignore anything I put in the damn JAVA_HOME spot.

**Comment by antgel** [comment] 2019-07-18 09:53
@jvoisin I'd really rather not reboot! :D

**Comment by fxthomas** [comment] 2019-07-19 22:03
FWIW I'm getting the same issue. I've been suspecting Lucene but haven't really had time to investigate.

**Comment by tesshucom** [comment] 2019-07-23 06:11
The creation and confirmation of this test case has been confirmed on Cent, Windows 10 and travis.
The failure of the test is very interesting in that it returns different values.

The structure of the test case with scan is based on the existing test case.
However, there are some parts where the method of testing is difficult in strict reproducibility.

AbstractAirsonicHomeTest#populateDatabaseOnlyOnce has the following description :
(There is no guarantee that it will lead to a solution.)

```

            try {
                // Await time to avoid scan failure.
                for (int i = 0; i < 10; i++) {
                    Thread.sleep(100);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            TestCaseUtils.execScan(mediaScannerService);
            System.out.println("--- Report of records count per table ---");
            Map<String, Integer> records = TestCaseUtils.recordsInAllTables(daoHelper);
            records.keySet().stream().filter(s ->
                    s.equals("MEDIA_FILE")
                    | s.equals("ARTIST")
                    | s.equals("MUSIC_FOLDER")
                    | s.equals("ALBUM"))
                    .forEach(tableName ->
                        System.out.println("\t" + tableName + " : " + records.get(tableName).toString()));
            System.out.println("--- *********************** ---");
            try {
                // Await for Lucene to finish writing(asynchronous).
                for (int i = 0; i < 5; i++) {
                    Thread.sleep(100);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

```

This sleep is a magic number.
Because Scan inherently includes processing that can not guarantee synchronization.
As a rule of thumb, machines with slow IO compared to CPU performance often fail test when the number is small.
It also happens in the real environment.

____
Local compilation can be avoided with the test option ``-Dmaven.test.skip=true`` if it is at least test certified by travis.

If it is possible to reproduce , corrective action is possible, but it can not be reproduced on my local machine :cry:

**Comment by angelawong** [comment] 2019-09-11 05:17
I tried to install airsonic from source as per the instructions found at:
https://airsonic.github.io/docs/install/source/

Did the following:
`/var/airsonic$ sudo mvn clean package -e`

Errors:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [  4.692 s]
[INFO] Subsonic REST API .................................. SUCCESS [ 33.804 s]
[INFO] Sonos API .......................................... SUCCESS [ 33.748 s]
[INFO] Airsonic Main ...................................... FAILURE [  8.867 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 min
[INFO] Finished at: 2019-09-11T01:13:21-04:00
[INFO] Final Memory: 51M/342M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:10.4.0-RELEASE: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1: Failed to read artifact descriptor for org.fourthline.cling:cling-core:jar:2.0.1: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.0.1 from/to teleal (http://teleal.org/m2): teleal.org: Name or service not known: Unknown host teleal.org: Name or service not known -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:10.4.0-RELEASE: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:10.4.0-RELEASE: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:181)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.fourthline.cling:cling-core:jar:2.0.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.0.1 from/to teleal (http://teleal.org/m2): teleal.org: Name or service not known
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	... 33 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.0.1 from/to teleal (http://teleal.org/m2): teleal.org: Name or service not known
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 36 more
Caused by: org.apache.maven.wagon.TransferFailedException: teleal.org: Name or service not known
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 41 more
Caused by: java.net.UnknownHostException: teleal.org: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:113)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:354)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
	... 50 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :airsonic-main

```

Any help or advice would be most appreciated. Thank you in advance.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

**Comment by fxthomas** [comment] 2019-09-20 06:23
No issue on my side.

**Comment by angelawong** [comment] 2019-09-20 23:24
This is what I am getting when I run:
airsonic$ mvn clean package

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Airsonic ........................................... SUCCESS [ 12.718 s]
[INFO] Subsonic REST API .................................. SUCCESS [01:48 min]
[INFO] Sonos API .......................................... SUCCESS [01:35 min]
[INFO] Airsonic Main ...................................... FAILURE [07:36 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:25 min
[INFO] Finished at: 2019-09-20T19:17:02-04:00
[INFO] Final Memory: 54M/342M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project airsonic-main: Could not resolve dependencies for project org.airsonic.player:airsonic-main:war:10.4.0-RELEASE: Failed to collect dependencies at org.fourthline.cling:cling-core:jar:2.0.1: Failed to read artifact descriptor for org.fourthline.cling:cling-core:jar:2.0.1: Could not transfer artifact org.fourthline.cling:cling-core:pom:2.0.1 from/to teleal (http://teleal.org/m2): teleal.org: Unknown host teleal.org -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :airsonic-main

**Comment by jvoisin** [comment] 2019-09-21 08:27
@angelawong try again, after removing your `~/.m2` folder, you're having a caching issue.

**Comment by tesshucom** [comment] 2020-05-11 08:58
#1277

It seems like it's too old, so I'll close it.
If you have any problems, please report again.

**Closed by tesshucom** 2020-05-11 08:58 UTC
Labels: in: test, status: feedback-provided, type: question
