### ISSUE TITLE
Airsonic loads resources over HTTP even behind a https proxy

### ISSUE THREAD

**Issue by captn3m0** [airsonic/airsonic#641] opened 2017-12-03 14:23 UTC
## Problem description

Similar to the issue reported in https://github.com/airsonic/airsonic/issues/373. I get the following warning in my console:

>Mixed Content: The page at 'https://hostname.tld/index' was loaded over HTTPS, but requested an insecure resource 'http://hostname.tld/home.view'. This request has been blocked; the content must be served over HTTPS.

### Steps to reproduce

I'm running airsonic behind a https proxy (traefik), with the following configuration:

`"traefik.frontend.passHostHeader" = "true"`

This results in the following headers being passed to airsonic:

```
X-Forwarded-For: 192.168.1.228
X-Forwarded-Host: hostname.tld
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: bcebbc893535
X-Real-Ip: 192.168.1.228
```

As per the docs at https://airsonic.github.io/docs/proxy/prerequisites/, this should be sufficient to run airsonic with a proxy server, but it doesn't seem to work.

I'm running the latest tagged docker image from https://hub.docker.com/r/airsonic/airsonic/tags/

Steps:

1. Run the latest airsonic image off docker
2. Run any frontend proxy over HTTPS
3. Try opening airsonic in browser

## System information

 * **Airsonic version**: 10.1.0-RELEASE – November 4, 2017
 * **Operating system**: ArchLinux, running using Docker version 17.10.0-ce
 * **Proxy server**: [Traefik v 1.5.0-rc1](https://github.com/containous/traefik/releases/tag/v1.5.0-rc1)
 * **Client**: Google Chrome

**Comment by avlouis** [comment] 2017-12-15 00:06
This is an issue and should be addressed in my opinion.
I have encountered it too.

A work around is to redirect http traffic to https.
In Apache httpd, the directive would be something like `Redirect permanent / https://example.com`

**Comment by captn3m0** [comment] 2017-12-15 07:43
I already have redirects setup, but they only work for GET requests. POST requests do not resubmit data for 302s, I think.

Some of the UI remains functional as a result

**Comment by muff1nman** [comment] 2017-12-16 17:51
Duplicate of #594

**Closed by muff1nman** 2017-12-16 17:51 UTC
Labels: issue
