### ISSUE TITLE
10.2.1 - Missing FFMPEG causes "Transcoded" MP3s the size of original FLACs

### ISSUE THREAD

**Issue by 4oo4** [airsonic/airsonic#894] opened 2019-03-01 19:10 UTC
## Problem description

I recently upgraded to 10.2.1 and at some point accidentally uninstalled ffmpeg, in the past when I haven't had it installed or symlinked to the correct place, I remember that the player would just freeze and refuse to play the file. However, I accidentally did this again, but Airsonic ended up downloading a 100+ MB file for what was supposed to be an MP3 of a 1 minute track.

### Steps to reproduce

1. Break the symlink in `/var/airsonic/transcode/ffmpeg` (or uninstall ffmpeg)
2. Attempt to play a high-resolution FLAC file in the Ultrasonic app, and download will be very slow and create very large files that are still labeled as MP3. Somehow it's still a playable MP3 file though?

## System information

 * **Airsonic version**: 10.2.1
 * **Operating system**: Ubuntu 16.04
 * **Proxy server**: nginx 1.15.8
 * **Client**: Ultrasonic Android App

Cheers

**Comment by eharris** [comment] 2019-10-15 04:45
This is kind of as-designed.  If the transcoder isn't installed, the code falls back to serving the original file, on the assumption that trying to play something is better than nothing.  The transcoder failure and fallback is also noted in the logs, and it is up to the server administrator to make sure that things are configured and working properly.

That being said, if a bitrate limit is configured, and is not being heeded, then that is a problem.  Other issues similar to this are being worked on as part of #1124.

**Comment by eharris** [comment] 2019-10-15 04:49
Closing this since the fallback functionality is working as designed.

**Closed by eharris** 2019-10-15 04:49 UTC

**Comment by 4oo4** [comment] 2019-10-15 21:20
@eharris Thanks, good to know. I think what confused me was that when it was serving the original file, which was a FLAC, the file extension was still MP3.
