### ISSUE TITLE
Add option for Volume Normalization

### ISSUE THREAD

**Issue by jallbrit** [airsonic/airsonic#1584] opened 2020-03-16 19:06 UTC
`mpd` supports not only replaygain, but also on-the-fly "audio normalization", which, according to their documentation:

> This setting enables on-the-fly normalization volume adjustment. This will result in the volume of all playing audio to be adjusted so the output has equal "loudness".

I find this feature incredibly useful, as you don't have to deal with replaygain tags which involve editing the files themselves. I would like to see this added as an Airsonic option, I assume server-side.

**Comment by randomnicode** [comment] 2020-03-16 22:58
I think this along with other stuff like play speed (for instance, play something at twice or half the speed) are class of features that would be immensely helpful and would be easy to achieve with a better architected transcoding engine.

In the meantime, @jallbrit might I suggest just changing your transcoder to integrate the volume normalization filters in ffmpeg?

**Comment by eharris** [comment] 2020-03-16 23:51
Please see #525 and #1138 for discussions and workarounds on how to add this functionality to your instance.  Closing this as a dupe of the discussion already taking place in #525.

**Closed by eharris** 2020-03-16 23:51 UTC

**Comment by jallbrit** [comment] 2020-03-17 21:17
@randomnicode, I am attempting to implement the `loudnorm` filter and found an example that uses the filter like this:

```
ffmpeg -i input.wav -filter:a loudnorm output.wav
```

I am looking at the transcoding options on my Airsonic server see multiple places where the `-filter:a loudnorm` could go. Most of my files are already `.mp3`, and I use an app on my phone to stream from my Airsonic server. Since they're already `.mp3`, I would imagine the filter would be useless applied to the 4 default transcodings.

To see the `loudnorm` effects on my client app or through the web player or however I stream the music, where do I apply this filter within the configuration?
