### ISSUE TITLE
Web player stops at the beginning of the second song

### ISSUE THREAD

**Issue by RuralHunter** [airsonic/airsonic#1125] opened 2019-06-14 04:15 UTC
## Problem description

The web player can not play the next song when the current song ends.

### Steps to reproduce

Just open any album in web UI and play any song in it. The web player stops after the current song completes. At the server side I can see the error log:
```
2019-06-14 12:08:28.246  INFO --- o.a.p.c.StreamController                 : 127.0.0.1: Got HTTP range: 0-
2019-06-14 12:08:28.247  INFO --- o.a.p.io.PlayQueueInputStream            : 127.0.0.1: admin listening to 齐秦/丝路.MP3  //The first song
2019-06-14 12:12:47.348  INFO --- o.a.p.c.StreamController                 : 127.0.0.1: Got HTTP range: 0-
2019-06-14 12:12:47.350  INFO --- o.a.p.io.PlayQueueInputStream            : 127.0.0.1: admin listening to 齐秦/夜夜夜夜.MP3  //The next song
2019-06-14 12:12:47.416  INFO --- o.a.p.c.StreamController                 : 127.0.0.1: Client unexpectedly closed connection while loading http://localhost:8080/stream?player=1&id=6093 (java.io.IOException: Connection reset)
2019-06-14 12:12:47.430  INFO --- o.a.p.s.LoggingExceptionResolver         : 127.0.0.1: Client unexpectedly closed connection while loading http://localhost:8080/stream?player=1&id=6093 (java.io.IOException: Broken pipe)
```

## System information

 * **Airsonic version**: 10.3.1-RELEASE
 * **Operating system**: Apache Tomcat/8.5.40, java 1.8.0_212, Linux (746.2 MB / 955.5 MB)
 * **Proxy server**: None
 * **Client**: web UI, Firefox

## Additional notes

It was good in 10.2.1 as far as I can remember.

**Comment by RuralHunter** [comment] 2019-06-14 04:36
I just tested v10.3.0 and it is fine. So this must be a regression introduced in v10.3.1.

**Comment by RuralHunter** [comment] 2019-06-14 06:01
I tested v10.3.0 and it has the same issue. So this must be caused by some changes in v10.3.0.

**Comment by jvoisin** [comment] 2019-06-14 08:46
This should be addressed by #1080

**Comment by RuralHunter** [comment] 2019-06-14 09:34
Ah yes, thanks for the info.

**Comment by seitzbg** [comment] 2019-06-17 22:58
This is still broken, is it recommended to just downgrade ?

**Comment by jvoisin** [comment] 2019-06-18 00:10
You can help by testing #1080 :)

**Comment by seitzbg** [comment] 2019-06-18 23:01
Is there a .war I can use to test ?

**Comment by jvoisin** [comment] 2019-06-19 23:56
Nope, you will have to [build it yourself]( https://airsonic.github.io/docs/install/source/ ) :)

**Comment by seitzbg** [comment] 2019-06-20 03:13
Yeah, building it now.  Isn't a fast process lol!

**Comment by seitzbg** [comment] 2019-06-20 03:34
MUCH better here!  Seems to work as it is supposed to.

**Comment by jvoisin** [comment] 2019-06-20 10:25
Please add your comment on the pull-request so let everyone know that it's working for you.
This will help to make it merged faster :)

**Comment by seitzbg** [comment] 2019-06-23 01:54
Actually I suppose I built from master... and not the patch.

**Comment by RuralHunter** [comment] 2019-06-25 04:08
It might be browser related. My browser is firefox.

**Comment by dalecooper** [comment] 2019-06-25 07:18
> Actually I suppose I built from master... and not the patch so it's odd that my playlist worked properly...

Building from master solved this annoying problem for me too

**Comment by jmbannon** [comment] 2019-06-26 17:14
Don't think it's browser related - having this issue on both Chrome and Firefox.

**Comment by jamesiri** [comment] 2019-06-27 23:21
Can confirm it isn't browser related. I get the same failure in FF, Chrome, and Safari.

**Comment by eharris** [comment] 2019-07-31 15:07
This likely was fixed when #1080 was merged.  Can anyone confirm it is still occurring 10.4.0, which contained #1080?  If not, this should be closed.

**Comment by jvoisin** [comment] 2019-07-31 20:06
I can't reproduce this locally anymore.

**Comment by RuralHunter** [comment] 2019-08-02 04:14
I confirm this is fixed in 10.4.0

**Closed** 2019-08-02 04:14 UTC
Labels: critical

**Comment by kehrnal** [comment] 2019-08-25 03:42
I just upgraded to 10.4.0 from 10.2.1.  I had this issue occasionally in 10.2.1, but it's suddenly plaguing me in 10.4.0.

**Comment by aeleeds** [comment] 2019-08-31 22:56
I'm using 10.4.0 running on a raspberry pi 3b stretch accessed via chrome and it suddenly stopped working entirely:

> 
> 2019-08-31 23:53:02.234 INFO --- o.a.p.io.PlayQueueInputStream : 24.193.56.198: adam listening to Goofy June Bug/Ab Baars Trio + Vandermark - Goofy June Bug - 01 - Straws.mp3
> 2019-08-31 23:53:02.448 INFO --- o.a.p.c.StreamController : 24.193.56.198: Client unexpectedly closed connection while loading http://24.193.56.198:8080/airsonic/stream?player=6&id=4879 (java.io.IOException: Broken pipe)
> 2019-08-31 23:53:09.423 INFO --- o.a.p.io.PlayQueueInputStream : 24.193.56.198: adam listening to Goofy June Bug/Ab Baars Trio + Vandermark - Goofy June Bug - 01 - Straws.mp3
> 2019-08-31 23:53:09.598 INFO --- o.a.p.c.StreamController : 24.193.56.198: Client unexpectedly closed connection while loading http://24.193.56.198:8080/airsonic/stream?player=6&id=4879 (java.io.IOException: Broken pipe)

Not sure if this is the same issue or a new one.

**Comment by aeleeds** [comment] 2019-08-31 23:03
I'm having either the same issue or a very similar issue. Running 10.4.0 on a raspberry pi 3B+ w/ stretch, playing in latest Chrome on Mac 10.14.6. Was working mostly fine for the last month, with some glitches, now won't play at all. Still runs fine in Safari. But in Chrome:

>2019-08-31 23:53:02.234 INFO --- o.a.p.io.PlayQueueInputStream : 24.193.56.198: adam listening to Goofy June Bug/Ab Baars Trio + Vandermark - Goofy June Bug - 01 - Straws.mp3
2019-08-31 23:53:02.448 INFO --- o.a.p.c.StreamController : 24.193.56.198: Client unexpectedly closed connection while loading http://24.193.56.198:8080/airsonic/stream?player=6&id=4879 (java.io.IOException: Broken pipe)
2019-08-31 23:53:09.423 INFO --- o.a.p.io.PlayQueueInputStream : 24.193.56.198: adam listening to Goofy June Bug/Ab Baars Trio + Vandermark - Goofy June Bug - 01 - Straws.mp3
2019-08-31 23:53:09.598 INFO --- o.a.p.c.StreamController : 24.193.56.198: Client unexpectedly closed connection while loading http://24.193.56.198:8080/airsonic/stream?player=6&id=4879 (java.io.IOException: Broken pipe)

**Comment by Kautenja** [comment] 2020-01-04 17:45
still happens in 10.5.0 using Chrome. Safari works fine. More often than not, Chrome can't even start the first stream, let alone make it to the second one. I just get a bunch of "Client unexpectedly closed connection while loading" errors in the server log and nothing useful from the web client.

**Comment by Kautenja** [comment] 2020-01-04 17:46
firefox wont work either

**Comment by Shurov** [comment] 2020-04-21 21:18
still happens on 10.6.1

**Comment by RedGreen007** [comment] 2020-05-07 04:51
Still happening in 10.6.2

**Comment by kehrnal** [comment] 2020-05-14 14:13
Everything was good for me in 10.6.0, but now this is happening again in 10.6.2

**Comment by hboetes** [comment] 2020-09-26 18:31
> Still happening in 10.6.2

Same here, and what's more worrying, @fxthomas has gone AWOL, not that anyone can force him to do anything, but since May he hasn't committed anything. What happened?
