### ISSUE TITLE
Remove UI dependency to externally hosted static assets

### ISSUE THREAD

**Issue by zrav** [airsonic/airsonic#853] opened 2018-12-30 08:23 UTC
## Problem description

Currently Airsonics web-UI makes use of Google hosted font files. This causes problems in offline / airgapped networks.

### Steps to reproduce

Disconnect network from internet, access and use the Airsonic web-UI. Notice long delays, as the browser waits for the asset requests to time out.

## System information

 * **Airsonic version**: v10.1.2

## Additional notes

There's no reason these files couldn't be provided by Airsonic itself.

**Comment by jooola** [comment] 2018-12-30 14:36
Haha, this one has a big history ^^.

Duplicate of #174 #399

**Comment by jooola** [comment] 2018-12-30 14:38
Could be cherry picked from https://github.com/Libresonic/libresonic/pull/173

**Closed** 2019-03-31 23:20 UTC
Labels: issue
