### ISSUE TITLE
getAlbumList API method returns empty array.

### ISSUE THREAD

**Issue by wagnered** [airsonic/airsonic#706] opened 2018-03-02 02:53 UTC
Hi,

I am a developer on the ampache/ampache project. I have been working on updating our Subsonic API.

It works well with Subsonic API 1.16.0, and the Subsonic server.

The problem seems to be that Airsonic does not conform to or there is a bug when trying to execute the getAlbumList with type = "alphabeticalByName" or "alphabeticalByArtist". From Airsonic it returns the albumList as an empty array. Or could there be a setting in Airsonic that needs to be set?

Thanks...

**Comment by jooola** [comment] 2018-03-02 03:10
Hi @wagnered 
Airsonic isn't planning to break with the subsonic API, It's too precious. We currently ship the subsonic API 1.15.0 since we didn't had time to upgrade to 1.16.0. But version has nothing ot do here...

So this is weird since I used it 4 hours ago while developing the new UI and everything is fine.

So IMO this is either a bug that return no/wrong error message either something is wrong on your side.
Well I don't know, would you paste the get url your use to retrieve those data ?

**Comment by jooola** [comment] 2018-03-02 03:13
See https://github.com/airsonic/airsonic-ui/blob/master/src/app/shared/service/album.service.ts#L40
Also if you want to test you can us the demo frontend https://airsonic.github.io/airsonic-ui/login

**Comment by wagnered** [comment] 2018-03-02 06:17
I don't know for sure what happened, but it started working.

I restarted the Airsonic server several times, then decided to move 7 albums to a different path.
when I created a new folder on that path, Airsonic successfully scanned in the files and displayed the artists in the sidebar.  This didn't happen after scanning the first path with all those albums.

Also, I was able to successfully create a remote Airsonic catalog in Ampache.
Other than the large number of albums in the first folder path I don't know what the difference is.

Could it be a timeout problem?

**Comment by jooola** [comment] 2018-03-02 14:23
You might have this issue #681
> I guess that proves the database has been populated.

Did you tried to access via Web UI ?

> Here is the assembled URL:
http://192.168.2.3:8080/rest/getAlbumList.view?u=admin&p=******&v=1.8.0&c=Ampache&f=json&type=alphabeticalByName

Why don't you use the Token + Salt auth system ?
https://server.net/rest/getAlbumList?type=random&size=40&offset=0&u=working&t=a16fe0e7d87b8f0b3c63caf565a0f798&s=SJbowkoou230fSR8wftl&c=Airsonic-UI&f=json&v=1.15.0

> Could it be a timeout problem?

Good question...

I guess not logs ?
Any particular details ?

**Comment by wagnered** [comment] 2018-03-02 18:05
@Afterster inherited ampache/ampache. Because it wasn't built on a framework, it is so disorganized and infested with bugs any enhancements had to depend on volunteer pull-requests.  Now that most of the bug infestation is gone, Afterster decided to recreate Ampache based on the Laravel framework. I am a late-comer to the Ampache development team and right now the only one who has any time..

The rationale in the comments indicates that as long as the ampache api can manage most of the methods listed on the [Subsonic API](http://www.subsonic.org/pages/api.jsp) page, the version does not really matter.  The developer's conclusion was that most apps don't tell the truth about the level anyway. The  1.8 API versin reveals how long ago the api was incorporated into Ampache.

Dsub and Subsonics also indicate no data" when trying to access the Airsonic server when the database has a large number of entries.

Here is the tail of the airsonic log:

2018-03-02 09:16:25.990  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 22000 entries.
2018-03-02 09:16:31.450  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 22250 entries.
2018-03-02 09:16:36.161  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 22500 entries.
2018-03-02 09:16:45.825  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 22750 entries.
2018-03-02 09:16:50.638  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 23000 entries.
2018-03-02 09:16:54.490  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 23250 entries.
2018-03-02 09:16:59.834  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 23500 entries.
2018-03-02 09:17:04.497  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 23750 entries.
2018-03-02 09:17:05.898  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 23843 entries.
2018-03-02 09:17:05.898  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
2018-03-02 09:17:05.943  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2018-03-02 09:17:05.948  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2018-03-02 09:17:06.005  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
2018-03-02 09:17:06.795  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2018-03-02 09:17:06.795  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
2018-03-02 09:21:08.768  INFO --- o.airsonic.player.dao.PlayerDao          : Created player 2.
2018-03-02 09:31:55.875  INFO --- o.airsonic.player.dao.PlayerDao          : Created player 3.

The db log shows data being inserted into the db:
SET AUTOCOMMIT FALSE
INSERT INTO MEDIA_FILE VALUES(4,'/media/backup/Music/Bob Marley','/media/backup/Music','DIRECTORY',NULL,NULL,NULL,'Bob Marley',NULL,NULL,NULL,NULL,NULL,NULL,FALSE,NULL,NULL,NULL,NULL,NULL,'/media/backup/Music',0,NULL,NULL,'2016-12-28 23:48:33.000000000','2016-12-28 23:48:33.000000000','2018-03-02 09:08:39.996000000','1969-12-31 16:00:00.000000000',TRUE,4)

I will revert back to the folder path with just a sample of albums and continue adding albums until Airsonic falters to get an idea what the limit might be.  I know it's not very "scientific" but it might give me time to work on the Ampache/Laravel version. :smile:

**Comment by wagnered** [comment] 2018-03-02 18:28
> You might have this issue #681

I don't think so.  There is no problem with the Subsonic server. It scans and displays the same quantity of artists/albums and displays them all on the index tab. Plus I can see them in the DSub or Subsonic app.

**Comment by jooola** [comment] 2018-03-02 22:52
I don't think the number of albums will change something. I don't have nay problems at all.
```
2018-02-05 22:01:30.906  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 69897 entries.
```

We need a way to reproduce this and the details of you installation.

**Comment by wagnered** [comment] 2018-03-03 00:52
So far, it seems like I can reproduce it all the time by specifying a folder path with very many files/

Airsonic 10.1.1-RELEASE
Fedora Release 26 (Twe13,926 songsnty Six) 64-bit
Kernel Linux 4.14.18-200.fc26.x86_64 x86_64
Apache2.4 running only ssl reverse proxy (not using https to access Airsonic)
Firefox 58.0.1 (64 bit)

I have been adding a dozen or so artists at a time then scanning each batch. no problem.

I am up to 13,926 songs. and the letter "L" on the side bar.
The Airsonic server is on the same system that all the other process are.  I wonder if it is a "priority" problem.

**Comment by wagnered** [comment] 2018-03-03 04:16
@jooola ,

My objective was to get Airsonic working adequately enough to debug the Ampache Subsonic API.

This has been accomplished by the above procedure so I will be closing this issue.

Thanks for your assistance. Much appreciated.

**Comment by wagnered** [comment] 2018-03-04 06:07
I decided to reopen it as I've been assisting someone who seems to have the same problem.

**Comment by jooola** [comment] 2018-03-04 13:50
Ok but still it looks duplicate of #681, so I think we can close it and go further on the other ticket

**Closed by jooola** 2018-03-04 13:50 UTC
Labels: issue, question, reproduce-steps-needed
