### ISSUE TITLE
DLNA does not work with docker

### ISSUE THREAD

**Issue by Gt1ult** [airsonic/airsonic#1379] opened 2019-10-29 15:37 UTC
Dear All,

I am using docker. Airsonic is installed using the networking in bridge mode port 4040. DLNA is not working. In the log the message "Enabling UPnP/DLNA media server" is reported. I looks like DLNA cannot be finalized. I would like to share my music to my yamaha media player.
I tried to use the networking in host as well, but nothing is changed.
Do you have any idea? Thank you in advance.

**Comment by randomnicode** [comment] 2019-10-30 21:08
Actually, just quickly glancing at it, I think the issue is that we're creating an ephemeral port for the DLNA service at startup that isn't exposed by the container (which seems to just expose 4040).

https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/service/UPnPService.java#L122

This is probably a bug. I wonder if anyone else has noticed this running inside docker? Are there any successful uses of DLNA from airsonic inside docker that might prove me wrong?

We should likely (a) fix a port for the DLNA so it's not ephemeral, and (b) expose it in the container

**Comment by Gt1ult** [comment] 2019-10-31 16:31
Hi Randomnicode, thank you so much for your help. I figured out how to do it. I am still learning and I am not so good.
So, I am using OpenMediaVault ,I set the networking to Hostand I typed the address http://192.168.2.100:4040/ in LAN Server address. It is working fine! Airsonic it is very cool. 
Now I have the problem to stream the music to my yamaha network player. I am trying to use jukebox but I am loosing :(

**Comment by fxthomas** [comment] 2019-11-28 22:11
Hey all, I'm doing a cleanup of the remaining issues: I believe this has been fixed in `master` and can be closed?

**Comment by tesshucom** [comment] 2019-12-14 13:30
It can be said ... that automatic allocation is no longer performed.
It will be silent feature change unless documented.
Will the description be added to the web page?

**Comment by fxthomas** [comment] 2019-12-15 17:09
Closing now, feel free to open a new issue if this still happens.

**Closed by fxthomas** 2019-12-15 17:09 UTC
