### ISSUE TITLE
Feature Request: Ability to scan a single folder on demand.

### ISSUE THREAD

**Issue by iarp** [airsonic/airsonic#1427] opened 2019-12-04 20:29 UTC
Some folders I have in airsonic do not change in months, while others may change minute to minute. It currently takes about 6-8 minutes to rescan all folders when it really only needs to scan 1, having a button next to each folder that initiates a scan of that folder only would be great. Thanks.

**Comment by eharris** [comment] 2019-12-04 20:58
This is a duplicate of #1084

**Closed by eharris** 2019-12-04 20:58 UTC
