### ISSUE TITLE
Playback interruptions while transcoding longer song/flac

### ISSUE THREAD

**Issue by rmzg** [airsonic/airsonic#1280] opened 2019-10-06 16:25 UTC
While listening to a longish song (12:24) encoded as flac I had several interruptions where playback would cease completely for 10-30 seconds then eventually resume. Server and client are both on the same wired lan and are running on relatively beefy machines.

System details:
Version: 10.4.0-RELEASE – July 13, 2019
Server:  Apache Tomcat/8.5.42, java 1.8.0_212, Linux (150.5 MB / 247.5 MB)

Console details:
```
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
```

Log details:
```
2019-10-06 16:08:05.821  INFO --- o.a.p.io.PlayQueueInputStream            : 172.16.40.147: admin listening to Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac
2019-10-06 16:08:05.825  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/airsonic/data/transcode/ffmpeg] [-i] [/airsonic/music/Agalloch/Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac] [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3] [-]
2019-10-06 16:09:23.626  INFO --- o.a.p.c.StreamController                 : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
2019-10-06 16:09:23.651  INFO --- o.a.p.s.LoggingExceptionResolver         : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
2019-10-06 16:12:08.370  INFO --- o.a.p.io.PlayQueueInputStream            : 172.16.40.147: admin listening to Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac
2019-10-06 16:12:08.373  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/airsonic/data/transcode/ffmpeg] [-i] [/airsonic/music/Agalloch/Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac] [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3] [-]
2019-10-06 16:13:11.674  INFO --- o.a.p.c.StreamController                 : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
2019-10-06 16:13:11.683  INFO --- o.a.p.s.LoggingExceptionResolver         : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
2019-10-06 16:15:34.330  INFO --- o.a.p.io.PlayQueueInputStream            : 172.16.40.147: admin listening to Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac
2019-10-06 16:15:34.334  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/airsonic/data/transcode/ffmpeg] [-i] [/airsonic/music/Agalloch/Marrow of the Spirit (2010)/A2 - Into The Painted Grey.flac] [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3] [-]
2019-10-06 16:16:43.120  INFO --- o.a.p.c.StreamController                 : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
2019-10-06 16:16:43.129  INFO --- o.a.p.s.LoggingExceptionResolver         : 172.16.40.147: Client unexpectedly closed connection while loading http://airsonic.home.rmz.gs/stream?player=1&id=3216 (java.io.IOException: Broken pipe)
```

Browser: Chrome/77, Windows 10

**Comment by eharris** [comment] 2019-10-08 10:11
This is a duplicate of #1276.

**Closed by eharris** 2019-10-08 10:11 UTC
Labels: duplicate
